# Generated by Django 3.0.6 on 2020-05-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='city')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='address')),
            ],
        ),
    ]
