# Generated by Django 3.0.6 on 2020-05-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_fill_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='email'),
        ),
    ]
