# Generated by Django 3.0.6 on 2020-05-17 17:25

from django.db import migrations
from django.conf import settings


def forwards_func(apps, schema_editor):
    if settings.DEBUG:
        try:
            from authapp.models import ShopUser

            ShopUser.objects.create_superuser("admin", "admin@google.com", "admin", age=33)
            ShopUser.objects.create_superuser("user", "user@google.com", "user", age=30)
        except:
            print("Cann't create super user for debug")


def reverse_func(apps, schema_editor):
    if settings.DEBUG:
        try:
            from authapp.models import ShopUser

            ShopUser.objects.all().delete()
        except:
            print("Cann't delete super user for debug")


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
